apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-and-node-manager-binding
subjects:
  - kind: ServiceAccount
    name: decentralized-k8s-controller-manager
    namespace: decentralized-k8s-system
roleRef:
  kind: ClusterRole
  name: pod-and-node-manager
  apiGroup: rbac.authorization.k8s.io
