# permissions for end users to view resourcemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcemonitor-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: decentralized-k8s
    app.kubernetes.io/part-of: decentralized-k8s
    app.kubernetes.io/managed-by: kustomize
  name: resourcemonitor-viewer-role
rules:
- apiGroups:
  - core.example.com
  resources:
  - resourcemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.example.com
  resources:
  - resourcemonitors/status
  verbs:
  - get
